language: cpp

os:
  - linux
  - osx
dist: trusty
sudo: required
compiler:
  - clang
  - gcc

env:
  - QT=53 BREW=ex   PPA=beineri/opt-qt532-trusty
  - QT=55 BREW=@5.5 PPA=beineri/opt-qt551-trusty
  - QT=57 BREW=ex   PPA=beineri/opt-qt571-trusty
  - QT=59 BREW=ex   PPA=beineri/opt-qt591-trusty
  - QT=510 BREW=@5.10

matrix:
  exclude:
    - { os: linux, compiler: clang }
    - { os: linux, env: QT=510 BREW=@5.10 }
    - { os: osx, compiler: gcc }
    - { os: osx, env: QT=53 BREW=ex   PPA=beineri/opt-qt532-trusty }
    - { os: osx, env: QT=57 BREW=ex   PPA=beineri/opt-qt571-trusty }
    - { os: osx, env: QT=59 BREW=ex   PPA=beineri/opt-qt591-trusty }

before_install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install qt${QT}base qt${QT}multimedia qt${QT}script'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cppcheck qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'

before_script:
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - qmake -v

script:
  - qmake "CONFIG+=debug" QtUkncBtl.pro
  - make
